version: "2"
services:
  cgi_server:
    depends_on:
      - mailhog

  task_scheduler:
    depends_on:
      - mailhog

  example_worker:
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: sh -c "echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt ${MAILHOG_PASSWORD})\" > /home/mailhog/htpasswd; MailHog -auth-file=/home/mailhog/htpasswd"
    ports:
      - "${MAILHOG_PORT}:8025"

  minio:
    ports:
      - "${MINIO_PORT}:9000"

  mysql:
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "${PHPMYADMIN_PORT}:80"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      HTTP_USER: "${BACKING_SERVICES_USER}"
      HTTP_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_HOSTS: "logs:redis:6379:0:${REDIS_PASSWORD},session:redis:6379:1:${REDIS_PASSWORD},cache:redis:6379:2:${REDIS_PASSWORD}"
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
